import path from "node:path";
import type {
  HubInfo,
  MaterializedFile,
  SpawnPlan,
  TaskSpec,
  VendorAdapter,
  VendorEvent,
} from "./types.js";
import { VENDOR_DIAG_PREFIX } from "./types.js";

/**
 * The `kimi` vendor adapter — real delegation to Moonshot AI Kimi Code CLI
 * (`kimi` binary from `@moonshot-ai/kimi-code`). Built from public docs only
 * (`docs/research/kimi-code-cli.md`); no local binary verification was done.
 *
 * Headless one-shot: `kimi -p <prompt> --output-format stream-json` (research
 * §2–§3). MCP hub is project-scoped `.kimi-code/mcp.json` (research §7). Auth
 * is **not** a plain API-key env passthrough — provider keys must live in
 * config or ride the `KIMI_MODEL_*` env family (research §9). We isolate a
 * per-task `KIMI_CODE_HOME` and materialize a generated `config.toml` so the
 * user's `~/.kimi-code` never bleeds in; model/effort map onto `KIMI_MODEL_*`.
 *
 * Defensive gaps (research Gaps §1–§5):
 *  - Non-interactive `-S` + `-p` resume is UNVERIFIED → `resume()` falls back
 *    to the same fresh spawn as `prepare()` (no `-S`/`-r` until live-proven).
 *  - Stdout usage records are UNVERIFIED → usage stays absent (null on the
 *    task row) unless a numeric usage object actually appears on the stream.
 *  - Fatal-error event shape is UNVERIFIED → unknown lines stay opaque (`[]`);
 *    the raw JSONL log is the durable record; exit-without-report is failure
 *    at the engine layer.
 *
 * `listModels` is omitted: catalog JSON shape is UNVERIFIED (research §10).
 */

/** Default binary; override via `PARLEY_KIMI_BIN` (smoke tests, custom installs). */
const DEFAULT_KIMI_BIN = "kimi";

/**
 * Per-task private data root relative to `task.cwd`, pointed at by
 * `KIMI_CODE_HOME` (research §9). Isolates config/sessions/logs from
 * `~/.kimi-code`.
 */
const CODE_HOME_REL = ".parley-kimi";

/** Project-scoped MCP config path (research §7 — overrides same-named user entries). */
const MCP_JSON_REL = ".kimi-code/mcp.json";

/** Generated config under the isolated home. */
const CONFIG_TOML_REL = `${CODE_HOME_REL}/config.toml`;

const MCP_SERVER_NAME = "parley";

/**
 * Headroom (ms) added to answerTimeoutMs for `toolTimeoutMs` in mcp.json
 * (research §7 — same class of gotcha as codex `tool_timeout_sec`).
 */
const TOOL_TIMEOUT_HEADROOM_MS = 60_000;

/**
 * Parent-env keys from the documented `KIMI_MODEL_*` family (research §9).
 * Forward only these — never `KIMI_API_KEY` / `ANTHROPIC_API_KEY` / etc., which
 * the binary does not read automatically (research §9 "not general-purpose").
 */
const KIMI_MODEL_ENV_KEYS = [
  "KIMI_MODEL_NAME",
  "KIMI_MODEL_API_KEY",
  "KIMI_MODEL_PROVIDER_TYPE",
  "KIMI_MODEL_BASE_URL",
  "KIMI_MODEL_MAX_CONTEXT_SIZE",
  "KIMI_MODEL_CAPABILITIES",
  "KIMI_MODEL_DISPLAY_NAME",
  "KIMI_MODEL_MAX_OUTPUT_SIZE",
  "KIMI_MODEL_REASONING_KEY",
  "KIMI_MODEL_THINKING_EFFORT",
  "KIMI_MODEL_ADAPTIVE_THINKING",
] as const;

/** Shell-style tool names → `command` events (research §5 OpenAI-style tool_calls). */
const SHELL_TOOL_RE = /^(Shell|Bash|shell|bash|terminal|run_terminal|execute_command)/i;

/** File-edit tool names → `file_change` events. */
const FILE_TOOL_RE =
  /^(Write|Edit|StrReplace|write_file|edit_file|apply_diff|search_replace|create_file|delete_file)/i;

function toolTimeoutMs(answerTimeoutMs: number): number {
  return answerTimeoutMs + TOOL_TIMEOUT_HEADROOM_MS;
}

function codeHomeAbs(cwd: string): string {
  return path.resolve(cwd, CODE_HOME_REL);
}

/**
 * Project-scoped MCP hub entry (research §7). HTTP transport is the bare
 * `url` form (no `transport` key). Headers carry `x-parley-task` correlation.
 */
function mcpJson(hub: HubInfo, answerTimeoutMs: number): string {
  return (
    JSON.stringify(
      {
        mcpServers: {
          [MCP_SERVER_NAME]: {
            url: hub.url,
            headers: hub.headers,
            startupTimeoutMs: 30_000,
            toolTimeoutMs: toolTimeoutMs(answerTimeoutMs),
          },
        },
      },
      null,
      2,
    ) + "\n"
  );
}

/**
 * Minimal isolated `config.toml` (research §9). Auth keys are *not* written
 * here from shell env — operators inject via `vendors.kimi.env` `KIMI_MODEL_*`
 * (engine merges after prepare) or pre-provisioned provider tables. The file
 * exists so Kimi does not fall through to a missing home.
 */
function configToml(task: TaskSpec): string {
  const lines = [
    "# Generated by parley — do not edit; regenerated on every (re)spawn.",
    "# Isolated KIMI_CODE_HOME — no bleed from the operator's ~/.kimi-code.",
  ];
  // Default model alias when TaskSpec does not name one (research §1).
  if (task.model === null) {
    lines.push('default_model = "kimi-for-coding"');
  } else {
    // Also pin default so interactive leftovers under the home stay consistent.
    lines.push(`default_model = ${tomlString(task.model)}`);
  }
  return lines.join("\n") + "\n";
}

/** Minimal TOML string escape (quotes, backslash, control chars). */
function tomlString(value: string): string {
  const escaped = value
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"')
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  return `"${escaped}"`;
}

function asRecord(value: unknown): Record<string, unknown> | undefined {
  return typeof value === "object" && value !== null
    ? (value as Record<string, unknown>)
    : undefined;
}

function asString(value: unknown): string {
  return typeof value === "string" ? value : "";
}

/**
 * Pull a session id from a `role:meta` / resume-hint record (research §4 / §5).
 * Field name is only partially DOCS — accept several common spellings.
 */
function sessionIdFromMeta(event: Record<string, unknown>): string | undefined {
  for (const key of ["session_id", "sessionId", "id", "session"]) {
    const v = event[key];
    if (typeof v === "string" && v !== "") return v;
  }
  // Nested common shapes.
  const data = asRecord(event.data);
  if (data) {
    for (const key of ["session_id", "sessionId", "id"]) {
      const v = data[key];
      if (typeof v === "string" && v !== "") return v;
    }
  }
  // Content may be the bare id or a `kimi -r <id>` hint string.
  const content = asString(event.content);
  if (content !== "") {
    const hint = /(?:^|\s)(?:-r|--resume|--session|-S)\s+(\S+)/.exec(content);
    if (hint?.[1]) return hint[1];
    if (/^[A-Za-z0-9._:-]+$/.test(content.trim())) return content.trim();
  }
  return undefined;
}

/**
 * Map an optional usage-like object into VendorEvent.usage.
 * Only numeric fields are kept — null/absent keys are **not** invented as 0
 * (tri-state honesty: missing stdout usage ⇒ no usage event ⇒ null on row).
 */
function usageFromUnknown(value: unknown): Record<string, number> | undefined {
  const obj = asRecord(value);
  if (!obj) return undefined;
  const usage: Record<string, number> = {};
  for (const [key, v] of Object.entries(obj)) {
    if (typeof v === "number" && Number.isFinite(v)) usage[key] = v;
  }
  // Canonical aliases when harness names appear (best-effort; schema UNVERIFIED).
  if (typeof obj.input_tokens === "number") usage.input_tokens = obj.input_tokens;
  else if (typeof obj.input === "number") usage.input_tokens = obj.input;
  if (typeof obj.output_tokens === "number") usage.output_tokens = obj.output_tokens;
  else if (typeof obj.output === "number") usage.output_tokens = obj.output;
  if (typeof obj.cached_tokens === "number") usage.cached_tokens = obj.cached_tokens;
  else if (typeof obj.cache_read_tokens === "number") {
    usage.cached_tokens = obj.cache_read_tokens;
  }
  return Object.keys(usage).length > 0 ? usage : undefined;
}

/**
 * Normalize one assistant `tool_calls[]` entry into command/file_change/message
 * (research §5 OpenAI-style function tools).
 */
function eventsFromToolCall(tc: unknown): VendorEvent[] {
  const call = asRecord(tc);
  if (!call) return [];
  const fn = asRecord(call.function) ?? call;
  const name = asString(fn.name || call.name);
  if (name === "") return [];
  const argsRaw = fn.arguments ?? call.arguments ?? call.input;
  let text = name;
  if (typeof argsRaw === "string" && argsRaw !== "") {
    text = `${name} ${argsRaw}`;
  } else if (argsRaw !== undefined) {
    try {
      text = `${name} ${JSON.stringify(argsRaw)}`;
    } catch {
      text = name;
    }
  }
  if (SHELL_TOOL_RE.test(name)) return [{ kind: "command", text }];
  if (FILE_TOOL_RE.test(name)) return [{ kind: "file_change", text }];
  return [{ kind: "message", text: `tool:${text}` }];
}

export function createKimiAdapter(env: NodeJS.ProcessEnv = process.env): VendorAdapter {
  const bin = env.PARLEY_KIMI_BIN ?? DEFAULT_KIMI_BIN;

  /**
   * Env: isolated home + model/effort via `KIMI_MODEL_*` + selective parent
   * `KIMI_MODEL_*` forward. No `KIMI_API_KEY` / provider-key passthrough
   * (research §9 — those shell vars are not read automatically).
   */
  function baseEnv(task: TaskSpec): Record<string, string> {
    const result: Record<string, string> = {
      KIMI_CODE_HOME: codeHomeAbs(task.cwd),
    };
    // Parent `KIMI_MODEL_*` first, then TaskSpec model/effort override so the
    // delegated request always wins over ambient daemon env.
    for (const key of KIMI_MODEL_ENV_KEYS) {
      const value = env[key];
      if (value !== undefined) result[key] = value;
    }
    if (task.model !== null) {
      result.KIMI_MODEL_NAME = task.model;
    }
    if (task.effort !== null) {
      result.KIMI_MODEL_THINKING_EFFORT = task.effort;
    }
    return result;
  }

  function files(task: TaskSpec, hub: HubInfo): MaterializedFile[] {
    return [
      { path: CONFIG_TOML_REL, contents: configToml(task) },
      { path: MCP_JSON_REL, contents: mcpJson(hub, task.answerTimeoutMs) },
    ];
  }

  /**
   * Flags shared by fresh (and no-resume fallback) spawns. Prompt is always
   * `-p <text>` (never `-c` — that is `--continue` on current CLI, research §3).
   * extraArgs land in the flags region before any ambiguity with the prompt.
   */
  function commonArgv(task: TaskSpec): string[] {
    const argv = ["--output-format", "stream-json"];
    // research §8: no faithful sandbox/network matrix. Closest lever is
    // `--plan` for read-only exploration; workspace/full use print-mode afk
    // auto-approve (implicit with `-p`). network:false cannot be enforced.
    if (task.sandbox === "read-only") {
      argv.push("--plan");
    }
    if (task.model !== null) {
      argv.push("-m", task.model);
    }
    // extraArgs: flags region only (TaskSpec contract / ADR-0009).
    argv.push(...task.extraArgs);
    return argv;
  }

  function spawnPlan(task: TaskSpec, hub: HubInfo): SpawnPlan {
    return {
      // `-p` alone triggers headless print/afk mode (research §3 VERIFIED).
      argv: [bin, "-p", task.prompt, ...commonArgv(task)],
      env: baseEnv(task),
      files: files(task, hub),
      cwd: task.cwd,
    };
  }

  return {
    id: "kimi",
    childChannel: "mcp",
    // research §1: config-file default alias when nothing else names a model.
    defaultModel: "kimi-for-coding",

    prepare(task, hub): Promise<SpawnPlan> {
      // Fresh headless one-shot (research §2 / recommended shape):
      //   kimi -p <prompt> --output-format stream-json [-m model]
      return Promise.resolve(spawnPlan(task, hub));
    },

    resume(task, hub): Promise<SpawnPlan> {
      // research §4: combining `-S <id>` with `-p` for non-interactive follow-up
      // is UNVERIFIED. Shipping `-S` would silently mint a new session on a
      // stale id (docs: unknown id → new session) — a quiet failure mode.
      // Engine has no separate "unsupported resume → prepare" seam; fall back
      // to fresh spawn semantics here (same plan as prepare). Session ids are
      // still captured from the stream for observability / a future live probe.
      void task.sessionId; // intentionally ignored until resume is verified
      return Promise.resolve(spawnPlan(task, hub));
    },

    parseEvent(line: string): VendorEvent[] {
      let parsed: unknown;
      try {
        parsed = JSON.parse(line);
      } catch {
        // Non-JSON noise (stderr banners, human resume hints without JSON).
        // Scrape a `kimi -r <id>` hint if present; otherwise opaque.
        const hint = /kimi\s+(?:-r|--resume)\s+(\S+)/.exec(line);
        if (hint?.[1]) {
          return [{ kind: "session_meta", session_id: hint[1] }];
        }
        // Auth / permanent failure text on plain stderr (research §2 exit 1).
        if (
          /api[_\s-]?key|authentication|unauthorized|not logged in|login required/i.test(
            line,
          )
        ) {
          return [{ kind: "error", text: line.trim(), fatal: true }];
        }
        return []; // raw log keeps the line
      }

      const event = asRecord(parsed);
      if (!event) return [];

      // Explicit error shapes if they ever appear (research §5 UNVERIFIED).
      if (event.type === "error" || event.type === "fatal" || event.role === "error") {
        const text =
          asString(event.message) ||
          asString(event.content) ||
          asString(event.error) ||
          "kimi error";
        return [{ kind: "error", text, fatal: true }];
      }

      // Meta / session resume hint (research §4 / §5).
      const role = asString(event.role);
      const type = asString(event.type);
      if (
        role === "meta" ||
        type === "session.resume_hint" ||
        type === "session_resume_hint" ||
        type === "session"
      ) {
        const session_id = sessionIdFromMeta(event);
        const usage = usageFromUnknown(event.usage);
        if (session_id !== undefined || usage !== undefined) {
          return [
            {
              kind: "session_meta",
              ...(session_id !== undefined ? { session_id } : {}),
              ...(usage !== undefined ? { usage } : {}),
            },
          ];
        }
        return [];
      }

      // Optional top-level usage-only record (stdout usage UNVERIFIED — parse
      // if present, never invent).
      if (type === "usage" || event.usage !== undefined) {
        const usage = usageFromUnknown(event.usage ?? event);
        if (usage) return [{ kind: "session_meta", usage }];
        // Usage object present but all fields null/non-numeric → honest null
        // (no event; task usage stays null).
        if (type === "usage") return [];
      }

      if (role === "user") {
        // Echo of the prompt — not assistant progress.
        return [];
      }

      if (role === "assistant") {
        const out: VendorEvent[] = [];
        const content = event.content;
        if (typeof content === "string" && content !== "") {
          out.push({ kind: "message", text: content });
        } else if (Array.isArray(content)) {
          // Content-block shape (defensive — docs show string content).
          for (const block of content) {
            const b = asRecord(block);
            if (!b) continue;
            if (b.type === "text" && typeof b.text === "string" && b.text !== "") {
              out.push({ kind: "message", text: b.text });
            }
          }
        }
        if (Array.isArray(event.tool_calls)) {
          for (const tc of event.tool_calls) {
            out.push(...eventsFromToolCall(tc));
          }
        }
        // Optional usage on the assistant turn (UNVERIFIED).
        const usage = usageFromUnknown(event.usage);
        if (usage) out.push({ kind: "session_meta", usage });
        return out;
      }

      if (role === "tool") {
        // Tool results are progress noise for status display; raw log keeps them.
        // Surface as opaque unless content looks like a hard failure.
        const content = asString(event.content);
        if (/permission denied|tool.*denied|mcp.*fail/i.test(content)) {
          return [
            {
              kind: "error",
              text: `${VENDOR_DIAG_PREFIX} kimi tool result: ${content}`,
            },
          ];
        }
        return [];
      }

      // Unrecognized terminal/object shapes → opaque. Raw vendor.jsonl preserves
      // the line; the engine fails exit-without-report rather than inventing
      // success (research §5 gap on fatal-event taxonomy).
      return [];
    },

    sessionId(events: VendorEvent[]): string | undefined {
      for (let i = events.length - 1; i >= 0; i--) {
        const event = events[i];
        if (event?.kind === "session_meta" && event.session_id !== undefined) {
          return event.session_id;
        }
      }
      return undefined;
    },

    // listModels omitted — `kimi provider catalog list` JSON shape UNVERIFIED.
  };
}

/** Exported for tests that assert isolation paths. */
export const KIMI_CODE_HOME_REL = CODE_HOME_REL;
export const KIMI_MCP_JSON_REL = MCP_JSON_REL;
export const KIMI_CONFIG_TOML_REL = CONFIG_TOML_REL;
