import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Vitest global setup: guarantee the `@useparley/ui` bundle exists before the
 * suite runs. The daemon's UI-serving test (`packages/cli/tests/ui.test.ts`)
 * proves the *built* bundle is served via discovery (#65), so the built bundle
 * must be present — but it is generated by `vite build` and gitignored, not
 * committed. Build it here when missing so `pnpm test` is self-contained; a
 * present bundle (e.g. from an explicit `pnpm build`) is left as-is to keep
 * repeat runs fast.
 */
export default function setup(): void {
  const repoRoot = path.resolve(fileURLToPath(new URL(".", import.meta.url)), "..");
  const indexHtml = path.join(repoRoot, "packages", "ui", "www", "index.html");
  if (fs.existsSync(indexHtml)) return;
  execFileSync("pnpm", ["--filter", "@useparley/ui", "build"], {
    cwd: repoRoot,
    stdio: "inherit",
  });
}
